Repository minzzzun/Huggit, pull requests merged in 2025-03, with the labels that each got.

#10 [Feat] : 깃허브 레포 생성 기능 구현
  .DS_Store
  Huggit.xcodeproj/project.pbxproj
  Huggit/.DS_Store
  Huggit/Managers/GithubAPIManagers/GithubRepoManager.swift
  Huggit/Models/GithubModels/GithubRepository.swift
  Huggit/Utils/GitHubConfig.swift
  Huggit/ViewModels/OnboardingViewModels/GithubLoginViewModel.swift
  Huggit/Views/OnboardingViews/VelogView.swift
Labels: Feature

#11 [Feat]: Velog 불러오기, HomeHeaderView 커밋수 및 연속일 연결, AppBar 구현
  .DS_Store
  Huggit.xcodeproj/project.pbxproj
  Huggit/Managers/VelogAPIManagers/VelogGraphQLManager.swift
  Huggit/Managers/VelogAPIManagers/VelogGraphQLQueries.swift
  Huggit/Managers/VelogAPIManagers/VelogPostManager.swift
  Huggit/Models/BlogModels/VelogModels/VelogResponseModels/VelogPostsResponse.swift
  Huggit/Models/GithubModels/GithubCommitModels/GithubResponseModels/ContributionCountsInPeriodResponse.swift
  Huggit/Models/GithubModels/GithubCommitModels/GithubResponseModels/ContributionDetailsResponse.swift
  Huggit/Models/GithubModels/GithubCommitModels/GithubResponseModels/RepoContributionDetailsResponse.swift
  Huggit/Utils/GitHubConfig.swift
  Huggit/ViewModels/HomeViewModels/CommitListViewModel.swift
  Huggit/ViewModels/HomeViewModels/HomeHeaderViewModel.swift
  Huggit/ViewModels/HomeViewModels/HomeViewModel.swift
  Huggit/Views/AppBarView.swift
  Huggit/Views/ContentView.swift
  Huggit/Views/HomeViews/CommitListViews/CommitListView.swift
  Huggit/Views/HomeViews/HomeHeaderViews/HomeHeaderView.swift
  Huggit/Views/HomeViews/HomeView.swift
  Huggit/Views/MyPageViews/MyPageView.swift
Labels: API, Feature, Style, Chore

#12 [Feat]: 마이페이지 UI, [Fix]: CommitDetailView 화면 넘어가면 달력 셀 위에 나올 수 있게 수정, [Chore]: 홈 헤더 스탬프 로직 일부 수정
  Huggit/Assets.xcassets/Mypage/Contents.json
  Huggit/Assets.xcassets/Mypage/feedback.imageset/Contents.json
  Huggit/Assets.xcassets/Mypage/feedback.imageset/feedback.png
  Huggit/Utils/String/String.swift
  Huggit/ViewModels/HomeViewModels/HomeHeaderViewModel.swift
  Huggit/ViewModels/HomeViewModels/HomeViewModel.swift
  Huggit/Views/AppBarView.swift
  Huggit/Views/HomeViews/CalendarViews/CalendarCellView.swift
  Huggit/Views/HomeViews/CalendarViews/CalendarHeaderViews/MonthSelectionModalView.swift
  Huggit/Views/HomeViews/CalendarViews/CalendarView.swift
  Huggit/Views/HomeViews/CommitDetailViews/CommitDetailView.swift
  Huggit/Views/HomeViews/HomeHeaderViews/HomeHeaderView.swift
  Huggit/Views/HomeViews/HomeView.swift
  Huggit/Views/MyPageViews/AccountInfoViews/AccountButtonView.swift
  Huggit/Views/MyPageViews/AccountInfoViews/AccountInfoView.swift
  Huggit/Views/MyPageViews/FeedbackView.swift
  Huggit/Views/MyPageViews/MyPageView.swift
  Huggit/Views/MyPageViews/UseInfoView.swift
  Huggit/Views/MyPageViews/UserInfoView.swift
Labels: Bug, Style, Chore

#13 [Fix] : 레포 생성시 디코딩에러 수정
  .DS_Store
  Huggit.xcodeproj/project.pbxproj
  Huggit/.DS_Store
  Huggit/Managers/GithubAPIManagers/GithubRepoManager.swift
  Huggit/Models/GithubModels/GithubRepository.swift
  Huggit/Utils/GitHubConfig.swift
  Huggit/ViewModels/OnboardingViewModels/GithubLoginViewModel.swift
  Managers/GithubAPIManager.swift
  Models/GithubAPIError.swift
  ViewModels/CreateRepositoryViewModel.swift
Labels: Bug

#15 [Feat] : Tistory 크롤링 기능구현 완료
  Huggit.xcodeproj/project.pbxproj
  Huggit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huggit/Managers/TistoryAPIManagers/TistoryPostManager.swift
  Huggit/ViewModels/HomeViewModels/CommitListViewModel.swift
  Huggit/Views/ContentView.swift
Labels: Feature

#17 [Feat] : 커밋 내용 형식 조정 (.md 파일로)
  Huggit.xcodeproj/project.pbxproj
  Huggit/ViewModels/HomeViewModels/CommitCreateViewModel.swift
Labels: Style
